global using System.Reflection;
global using GestaoDePedidos.Application.Common.Interfaces;
global using GestaoDePedidos.Infrastructure.Data;
global using GestaoDePedidos.Infrastructure.Interceptors;
global using GestoDePedidos.Domain.Entities;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Diagnostics;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.Extensions.Configuration;